# ---------------------------------------------------------------
# Tw1nkle Config
# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Set default keywords (Use a comma to separate)
keywords: "Hexo, Tw1nkle"

# Specify the date when the site was setup
since: 2015

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# When running hexo in a subdirectory (e.g. domain.tld/blog)
# Remove leading slashes ( "/archives" -> "archives" )
menu:
  Home: /
  # Categories: /categories
  About: /about
  Archive: /archives/
  GitHub: https://github.com/Phantr4x
  # Tags: /tags
  # Commonweal: /404.html
  RSS: /atom.xml


# Place your favicon to /source directory.
favicon: favicon.png
logo: logo-512.png

# Google fonts CDN
googlefonts: false


archive_generator:
  per_page: 0
  yearly: false
  monthly: false
  daily: false


# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------




#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! ---------------------------------------------------------------

# Motion
# use_motion: true

# Fancybox
# fancybox: true

# Static files
vendors: vendors
css: css
js: js
images: images

# Theme version
version: 0.1.0
