# ---------------------------------------------------------------
# Inky Config
# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Set default keywords (Use a comma to separate)
keywords: Hexo, Inky

# Copyright Information
## Specify the date when the site was setup
since: 2015

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# When running hexo in a subdirectory (e.g. domain.tld/blog)
# Remove leading slashes ( "/archives" -> "archives" )

# home: /
archives: /archives
categories: /categories
tags: /tags
about: /about.html
rss: /atom.xml
# Commonweal: /404.html


# Place your favicon to /source directory.
favicon: favicon.png

# Google fonts CDN
googlefonts: false

# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------

# Comment
# e.g disqus: [your_shortname]
# disqus: sh7me
# dove:
# livere:
gitalk:
  enable: true
  clientID: ef2c9f810d80f033c0f6
  clientSecret: aa0c9d3ffbf5fb711378999b9dc679142d3c6047
  repo: blog-comments
  owner: sh7me
  admin:
    - sh7me
  labels:
    - gitalk
  pagerDirection: last
# valine:
#   enable: true
#   appid: vtrzX1OeP3kTNUHa5biL0jnA-gzGzoHsz
#   appkey: Ipq1AXhLKUfr29vqQit1f0WG

# Analytics
# google-analytics:
google_analytics:
# baidu-analytics:
baidu_analytics: # //hm.baidu.com/hm.js?b41062d843f1043fb808af9b7f4e7dd6


#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! ---------------------------------------------------------------
