# ---------------------------------------------------------------
# Tw1nkle Config
# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Set default keywords (Use a comma to separate)
keywords: "Hexo, Tw1nkle"

# Rss
rss: /atom.xml

# Copyright Information
## Specify the date when the site was setup
since: 2015

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# When running hexo in a subdirectory (e.g. domain.tld/blog)
# Remove leading slashes ( "/archives" -> "archives" )
menu:
  home: /
  archives: /archives
  categories: /categories
  tags: /tags
  about: /about
  rss: /atom.xml
  # Commonweal: /404.html

# Place your favicon to /source directory.
favicon: favicon.png
logo: logo-512.png

# Google fonts CDN
googlefonts: false



archive_generator:
  per_page: 0
  yearly: false
  monthly: false
  daily: false


# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------

# Comment
# e.g disqus: Phantr4x
disqus: Phantr4x
duoshuo:

# Analytics
# google-analytics:
google_analytics:
# baidu-analytics:
baidu_analytics: //hm.baidu.com/hm.js?b41062d843f1043fb808af9b7f4e7dd6




#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! ---------------------------------------------------------------

# Theme version
version: 0.1.0
